# Generated by Django 2.2.10 on 2021-03-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rawfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, null=True)),
                ('mtime', models.IntegerField(null=True)),
                ('vidLength', models.FloatField(null=True)),
                ('vidNumFrames', models.IntegerField(null=True)),
                ('camFirmware', models.CharField(max_length=100, null=True)),
                ('fullPath', models.CharField(max_length=2000, null=True)),
                ('fileName', models.CharField(max_length=2000, null=True)),
                ('fileFullName', models.CharField(max_length=2000, null=True)),
                ('gpsInfoFullPath', models.CharField(max_length=2000, null=True)),
                ('recNum', models.IntegerField(null=True)),
                ('seqNum', models.IntegerField(null=True)),
                ('firstGoodGPSLat', models.FloatField(null=True)),
                ('firstGoodGPSLon', models.FloatField(null=True)),
                ('lastGoodGPSLat', models.FloatField(null=True)),
                ('lastGoodGPSLon', models.FloatField(null=True)),
                ('tagLocationLat', models.FloatField(null=True)),
                ('tagLocationLon', models.FloatField(null=True)),
                ('timeZone', models.CharField(max_length=100, null=True)),
                ('timeOffset', models.IntegerField(null=True)),
                ('country_int', models.CharField(max_length=2000, null=True)),
                ('country_loc', models.CharField(max_length=2000, null=True)),
                ('county', models.CharField(max_length=2000, null=True)),
                ('municipality', models.CharField(max_length=2000, null=True)),
                ('UTCtime', models.IntegerField(null=True)),
                ('localTime', models.IntegerField(null=True)),
                ('trail', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
