# Generated by Django 2.2.10 on 2021-03-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfile',
            name='UTCtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='localTime',
            field=models.DateTimeField(null=True),
        ),
    ]
