# Generated by Django 2.2.10 on 2021-03-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='GPSfreq',
            field=models.FloatField(null=True),
        ),
    ]
