# Generated by Django 2.2.10 on 2021-04-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='unsureLat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='unsureLon',
            field=models.FloatField(null=True),
        ),
    ]
