# Generated by Django 2.2.10 on 2021-03-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
