# Generated by Django 2.2.10 on 2021-03-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210328_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawfile',
            name='localTime',
        ),
        migrations.AddField(
            model_name='rawfile',
            name='UTCtimeStr',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='localTimeStr',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='UTCtime',
            field=models.IntegerField(null=True),
        ),
    ]
