# Generated by Django 2.2.10 on 2021-03-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210324_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfile',
            name='lat',
            field=models.FloatField(null=True),
        ),
    ]
