# Generated by Django 2.2.10 on 2021-04-13 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210413_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Milliseconds', models.IntegerField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Altitude', models.FloatField()),
                ('Speed', models.FloatField()),
                ('Speed3D', models.FloatField()),
                ('TS', models.IntegerField()),
                ('GpsAccuracy', models.IntegerField()),
                ('GpsFix', models.IntegerField()),
                ('rawfileKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Rawfile')),
            ],
        ),
    ]
