# Generated by Django 2.2.10 on 2021-03-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210328_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawfile',
            old_name='UTCtime',
            new_name='GMTtime',
        ),
        migrations.RenameField(
            model_name='rawfile',
            old_name='UTCtimeStr',
            new_name='GMTtimeStr',
        ),
    ]
