# Generated by Django 2.2.10 on 2021-04-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gpsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='view',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
