# Generated by Django 2.2.10 on 2021-05-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rawfile_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='vehicle',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
