# Generated by Django 2.2.10 on 2021-03-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210324_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
