# Generated by Django 2.2.10 on 2021-05-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rawfile_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rawfile_logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=30, null=True)),
                ('textlog', models.TextField()),
                ('overpassServername', models.CharField(max_length=200, null=True)),
                ('overpassGenerator', models.CharField(max_length=200, null=True)),
                ('overpassVersion', models.CharField(max_length=10, null=True)),
                ('overpassTimstampOSMBase', models.CharField(max_length=24, null=True)),
                ('overpassTimstampAreasBase', models.CharField(max_length=24, null=True)),
                ('rawfileKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Rawfile')),
            ],
        ),
    ]
