# Generated by Django 2.2.10 on 2021-03-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210324_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfile',
            name='lat',
            field=models.FloatField(default=60.53),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='lon',
            field=models.FloatField(default=5.14),
        ),
    ]
